# @author MILO-GAO(\u9ad8\u632f\u9298)@2020 #

status=INFO

appender.console.type=Console
appender.console.name=LogToConsole
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss} %p %C{16} [%L] %m%n

appender.rolling.type=RollingFile
appender.rolling.name=LogToRollingFile
appender.rolling.fileName=/home/mvpadm/logs/AP_log/mvp.log
appender.rolling.filePattern=/home/mvpadm/logs/AP_log/$${date:yyyy-MM}/mvp-%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.layout.type=PatternLayout
appender.rolling.layout.pattern=%d{HH:mm:ss} %p %C{16} [%L] %m%n
appender.rolling.policies.type=Policies
appender.rolling.policies.time.type=TimeBasedTriggeringPolicy
appender.rolling.policies.size.type=SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=20MB
appender.rolling.strategy.type=DefaultRolloverStrategy
appender.rolling.strategy.max=50
appender.rolling.strategy.fileIndex=min

logger.app.name=com.fubon.mvp
logger.app.level=INFO
logger.app.additivity=false
logger.app.appenderRef.rolling.ref=LogToRollingFile
logger.app.appenderRef.console.ref=LogToConsole

# ============================================================
# JPA / JDBC SQL 日誌顯示
# ============================================================
logger.hibernate.name=org.hibernate.SQL
logger.hibernate.level=DEBUG
logger.hibernate.additivity=false
logger.hibernate.appenderRef.console.ref=LogToConsole

logger.hibernate_params.name=org.hibernate.type.descriptor.sql.BasicBinder
logger.hibernate_params.level=TRACE
logger.hibernate_params.additivity=false
logger.hibernate_params.appenderRef.console.ref=LogToConsole

logger.jdbc.name=org.springframework.jdbc.core
logger.jdbc.level=DEBUG
logger.jdbc.additivity=false
logger.jdbc.appenderRef.console.ref=LogToConsole

rootLogger.level=INFO
rootLogger.appenderRef.stdout.ref=LogToConsole